---
- name: Removing unsed dependencies
  hosts: node2.example.com
  vars:
   - apt_cache: /var/cache/apt/archievs/
  become: yes
  tasks:
  - name: Removing apt dependencies
    apt:
      autoremove: yes
      purge: yes

  - name: collecting list of apt-cache
    find:
      paths: "{{ apt_cache }}"
      patterns: "*.deb"
    register: files_to_delete

  - name: These files are getting deleted
    debug:
      msg: "{{ files_to_delete }}" 
...
