---
# tasks file for web
- name: Execusing main.yml file
  tasks:
  - include: centos.yml
    when: ansible_facts['os_family'] == "RedHat"
  - include: debian.yml
    when: ansible_os_family == "Debian"
