---
# tasks file for web
  - name: centos 
    include_tasks: centos.yml
    when: ansible_facts['os_family'] == 'RedHat'
  - name: ubuntu
    include_tasks: debian.yml
    when: ansible_facts['os_family'] == 'Debian'

...
